spring:
  application:
    name: ai-resume-portfolio-builder
  
  datasource:
    url: jdbc:postgresql://dpg-d3160s0dl3ps73e3lddg-a.oregon-postgres.render.com:5432/resume_portfolio_builder
    username: resume_portfolio_builder_user
    password: ViEfLKIh9yeeno61M9pVOLpqjYrmzFtj
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin

server:
  port: 8080

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    com.resumebuilder: DEBUG
    org.springframework.security: DEBUG
